# fly.toml app configuration file generated for un-digital-library-report-api-2 on 2025-06-19T12:00:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'un-report-api'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"

  [http_service.concurrency]
    type = "connections"
    hard_limit = 550
    soft_limit = 500

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 